name: alphabeta
version: 0.1.0.0
github: "davidspies/alphabeta"
license: BSD3
author: "David Spies"
maintainer: "dnspies@gmail.com"
copyright: "2022 David Spies"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/davidspies/alphabeta#readme>

dependencies:
  - base >= 4.7 && < 5
  - memoize

ghc-options:
  - -Wall

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - StandaloneDeriving
  - TypeFamilies

library:
  source-dirs: src

tests:
  alphabeta-test:
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -Wno-missing-export-lists
      - -Wno-unsafe
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - alphabeta
      - containers
      - hspec
      - tasty
      - tasty-discover
      - tasty-hspec
      - vector
